<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CONTRACT\CONTRACT.csproj" />
    <ProjectReference Include="..\OnlineSchedule.BLL\OnlineSchedule.BLL.csproj" />
    <ProjectReference Include="..\OnlineSchedule.DAL\OnlineSchedule.DAL.csproj" />
    <ProjectReference Include="..\OnlineSchedule.UI\OnlineSchedule.UI.csproj" />
  </ItemGroup>

</Project>
